### PR TITLE
Add Formatting

### PR DESCRIPTION
**Pull request by huacnlee**
Relative: 

https://github.com/pest-parser/pest-fmt/pull/9

### CODE REVIEW

**Comment by Jamalam360** [comment]
Thanks for this! I'll take a look once I finish my refactoring (don't worry, I can do the maybe slightly painful merge 😂)

**Review by tomtau — COMMENTED** [review]
the new pest_fmt was just published: https://crates.io/crates/pest_fmt hopefully it works

**Comment by Jamalam360** [comment]
@huacnlee I think we should stick with normal NPM personally since it's the thing most people will have installed. Thoughts?

**Review by Jamalam360 — COMMENTED** [review]
lgtm apart from above question

**Comment by huacnlee** [comment]
Do you means Yarn?

If you care about that, I can remove it.

**Comment by huacnlee** [comment]
But my suggestion is that we shouldn't too much mind this, it's just a tool (Intact, even GitHub Action has built-in Yarn by default, and VS Code project also used it).

**Comment by Jamalam360** [comment]
Thank you for the contribution :) We will probably get publishing done this weekend for a beta, then I'll think about tower-LSP-ifying everything

**Pull request merged**
